# Generated by Django 4.1 on 2022-09-01 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Base",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "base_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.base",
                    ),
                ),
                ("name", models.CharField(max_length=124)),
                ("phone", models.CharField(max_length=11)),
                ("address", models.TextField()),
                ("equipement", models.CharField(max_length=225)),
                ("installation", models.DateTimeField(blank=True, null=True)),
                ("service", models.DateTimeField(blank=True, null=True)),
                ("maintenace", models.DateTimeField(blank=True, null=True)),
                ("staff", models.CharField(max_length=255)),
            ],
            options={"ordering": ("-created_at",),},
            bases=("app.base",),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "base_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.base",
                    ),
                ),
                ("debit", models.FloatField(blank=True, null=True)),
                ("credit", models.FloatField(blank=True, null=True)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("1", "Installation"),
                            ("2", "service"),
                            ("3", "maintance"),
                        ],
                        max_length=225,
                    ),
                ),
                ("payment_status", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="app.client",
                    ),
                ),
            ],
            options={"ordering": ("-created_at",),},
            bases=("app.base",),
        ),
    ]
