# Generated by Django 4.1 on 2022-09-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="staff",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
