# Generated by Django 4.1 on 2022-09-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_client_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="service_type",
            field=models.CharField(
                choices=[("1", "Installation"), ("2", "Service"), ("3", "Maintance")],
                default=2,
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_type",
            field=models.CharField(
                choices=[("1", "Paid"), ("2", "Not Paid")], max_length=225
            ),
        ),
    ]
