# Generated by Django 4.1 on 2022-09-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_transaction_service_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="transaction", name="payment_status",),
    ]
