# Generated by Django 4.1 on 2022-09-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_transaction_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="payment_type",
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="service_type",
            field=models.CharField(max_length=255),
        ),
    ]
