# Generated by Django 4.1 on 2022-09-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_transaction_payment_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="credit",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="debit",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
