# Generated by Django 4.1 on 2022-09-03 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_transaction_credit_alter_transaction_debit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "base_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.base",
                    ),
                ),
                ("name", models.CharField(max_length=124)),
                ("phone", models.CharField(max_length=11)),
                ("address", models.TextField()),
            ],
            options={"ordering": ("-created_at",),},
            bases=("app.base",),
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "base_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.base",
                    ),
                ),
                ("item", models.CharField(blank=True, max_length=255, null=True)),
                ("desc", models.TextField(blank=True, null=True)),
                ("qty", models.IntegerField(blank=True, null=True)),
                ("price", models.FloatField(blank=True, null=True)),
                ("pay", models.FloatField(blank=True, null=True)),
                ("balance", models.FloatField(blank=True, null=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="app.client",
                    ),
                ),
            ],
            bases=("app.base",),
        ),
    ]
