# Generated by Django 4.1 on 2022-09-03 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_vendor_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to="app.vendor",
            ),
        ),
    ]
