# Generated by Django 4.1 on 2022-09-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_expense"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="total",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
